baseURL = 'https://kunfucutsman.neocities.org/'
languageCode = 'en-us'
title = "KFCMan's Odd Corner of the Internet"
timeZone = 'America/Mexico_City'
enableGitInfo = true

[taxonomies]
    tag = 'tags'
    series = 'series'

[[redirects]]
    from = '/**'
    status = 404
    to = '/not_found.html'

[markup.tableOfContents]
    endLevel = 6

[markup.goldmark.renderer]
    unsafe = true