baseURL = 'https://kunfucutsman.neocities.org/'
languageCode = 'en-us'
title = "KFCMan's Odd Corner of the Internet"
timeZone = 'America/Mexico_City'
enableGitInfo = true

disableKinds = ['sitemap']

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html']

[taxonomies]
    tag = 'tags'
    series = 'series'

[[redirects]]
    from = '/**'
    status = 404
    to = '/not_found.html'

[markup.tableOfContents]
    endLevel = 6

[markup.highlight]
    style = 'fruity'

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.extensions]
    strikethrough = false

[markup.goldmark.extensions.extras.delete]
    enable = true
[markup.goldmark.extensions.extras.subscript]
    enable = true
[markup.goldmark.extensions.extras.superscript]
    enable = true