baseURL = 'https://kunfucutsman.neocities.org/'
languageCode = 'en-us'
title = "KFCMan's Odd Corner of the Internet"

[taxonomies]
    tag = 'tags'
    series = 'series'

[[redirects]]
    from = '/**'
    status = 404
    to = '/not_found.html'

[markup.goldmark.renderer]
    unsafe = true